### ISSUE TITLE
[Cold Hearted] Icecrown

### ISSUE THREAD

**Issue by Dotcom92** [RR2739-VCN/Redrum-PvP#1]
Zone-Icecrown

Proto drake suppose to fly faster then this its barely moving.

https://youtu.be/dQvtAOwBlF0  video of me doing the quest

How the quest should function-
https://www.youtube.com/watch?v=M_484Zsfmec

**Comment by D-CellX** [comment]
Adding this to the list of next update. thank you

**Comment by D-CellX** [comment]
Applied a fix to redrum,, wrong enums

**Comment by D-CellX** [comment]
#1 is now working correctly,. it might not work 100% Blizzlike but it will do the job.
