### ISSUE TITLE
All healing spells for shaman

### ISSUE THREAD

**Issue by Lordmatsi** [RR2739-VCN/Redrum-PvP#12]
**Describe the bug**
Restoration Shaman talents make healing spells cost a lot less mana, but sometimes it "bugs" out and makes all the spells cost 100%.

**To Reproduce**
It happens randomly, but mostly after you leave a Battleground

**Expected behavior**
I expect the spells to cost less mana
![WoWScrnShot_040319_204609](https://user-images.githubusercontent.com/49250483/55504978-57b07580-5652-11e9-9da7-5b6be048d5f4.jpg)
![WoWScrnShot_040319_204627](https://user-images.githubusercontent.com/49250483/55504979-57b07580-5652-11e9-8f63-4c03499edc7d.jpg)

**Comment by Lordmatsi** [comment]
These screenshots are taken before and after a relog.

**Comment by D-CellX** [comment]
Thank you for the report @Lordmatsi , Just to confirm this bug, does this happen to all spells or a specific type spells?

**Comment by Lordmatsi** [comment]
For what i\ve senn, its all healing spells atleast; Riptide, lesser healing wave, healing wave

**Comment by D-CellX** [comment]
Thank you, will be looking to the issue
