### ISSUE TITLE
Cast Spell/Ability

### ISSUE THREAD

**Issue by Paccijazmin** [RR2739-VCN/Redrum-PvP#14]
### **Spell in warrior**
When Warrior Want to Do Spell For Defensive
he Use [Defensive Stance] for can use
[Shiled Wall] and [Shield Block] But If He Change To [Battel  Stance]
The Spell [Shield Wall] and Spell [Shield Block] They Dont Gone They Stay
like That mistake It should be not because if Every Warrior Can Do That
Can Defensive 100% and Dmg 100%, That's what and i report him to help us

**Expected behavior**
like That mistake It should be not because if Every Warrior Can Do That
Can Defensive 100% and Dmg 100%, That's what i find and i report him to help us

**Additional context**
Thank you for your times V.c.n wow 4LIFE <3

**Comment by D-CellX** [comment]
Thank you for the report. It will be added as priority to fix,

**Comment by Paccijazmin** [comment]
No thanks on duty,Thanks for the good hosting vcnwow

**Comment by RR2739-VCN** [comment]
Corrected the issue with the next update. Will reboot shortly

`            // most used check: shield only
            if (spellInfo->EquippedItemSubClassMask & ((1 << ITEM_SUBCLASS_ARMOR_BUCKLER) | (1 << ITEM_SUBCLASS_ARMOR_SHIELD)))
            {
                if (Item* item = GetUseableItemByPos(INVENTORY_SLOT_BAG_0, EQUIPMENT_SLOT_OFFHAND))
                    if (item != ignoreItem && item->IsFitToSpellRequirements(spellInfo))
                        return true;

                // special check to filter things like Shield Wall, the aura is not permanent and must stay even without required item
                if (!spellInfo->IsPassive())
                {
                    for (uint8 i = 0; i < MAX_SPELL_EFFECTS; ++i)
                        if (spellInfo->Effects[i].IsAura())
                            return true;
                }
            }
`

**Comment by D-CellX** [comment]
According to @ariel- in #21594 (comment) it is intended (Blizzlike) behaviour
https://github.com/TrinityCore/TrinityCore/issues/22526

> @Aokromes Aokromes added the Invalid-Intended/WontFix/Blizzlike  label on Sep 27, 2018
