### ISSUE TITLE
Lifebloom

### ISSUE THREAD

**Issue by Zoodymer** [RR2739-VCN/Redrum-PvP#15]
Power Lifebloom  is very weak
Full pve resto 10.5hc <-- 3x stack = 5k  crit
Pvp feral <-- 3x stack = 2.5k

my wf feral on another server can handle 6-7k crit
Resto pvp 10k max.
![WoWScrnShot_040919_103255](https://user-images.githubusercontent.com/49433485/55786502-a7f56080-5ab4-11e9-8a68-9c56b5f39fc4.jpg)
 Thank you so much.

**Comment by D-CellX** [comment]
The issue was fixed.
