### ISSUE TITLE
Bryntroll, the Bone Arbiter

### ISSUE THREAD

**Issue by Lordmatsi** [RR2739-VCN/Redrum-PvP#17]
**Describe the bug**
Bryntroll, the Bone Arbiter proc doesnt proc at all.

**To Reproduce**
1. Buy Bryntroll, the Bone Arbiter HC or Normal version
2. Equip Weapon
3. Hit targets
4. See that the proc isnt working

**Expected behavior**
There is a chance for the weapon to heal you when you hit a target.

**Screenshots**
No screenshots can capture the problem

**Additional context**
No.

**Comment by D-CellX** [comment]
Thank you for the report  we will be looking in to it, will update this post shortly.

**Comment by TonyFonTony** [comment]
The proc seems to work fine. The chance is quite low but blizzlike.

![PROC](https://user-images.githubusercontent.com/49968539/56706607-dee18e00-66d2-11e9-8bf6-45df34b3fc56.png)

**Comment by Lordmatsi** [comment]
Guess i have just been unlucky then👍🏼
