### ISSUE TITLE
Spells : Seal of Vengeance

### ISSUE THREAD

**Issue by Min0rity81** [RR2739-VCN/Redrum-PvP#18]
**Describe the bug**
Seal of Vengeance scales too much;
https://wow.gamepedia.com/Seal_of_Vengeance

**To Reproduce**
Grab a paladin with SoV, Donor sword(fel twisted blade), no gear. No talents, only glyph of Judgement
Buff self with might (for AP bonus to test)
attack dummy till 5 stacks.

**Expected behavior**
WoWpedia's formula of SoV which is: 0.013*SPH+0.025*AP*5 (*5 represents 5 stacks). 
Using the stats of my paladin, the formula is as shown:
0.013*948+0.025*1116*5 = 151.824 (since we dont use decimals in this calculation); 152 per tick at 5 stacks. 
Screenshot below is its current ticks of 193 which is +41 damage than its intended calculation.

With the 10% increased judgment dmg via Glyph + 50% judgement damage from SoV at 5 stacks (total of 60%) with the current formula: [1+0.22*SPH+0.14*AP].
Using my paladins stats; [1+0.22*948+0.14*1116] + 10% = 402.38 (0 stacks). 
At 5 stacks the damage is increased by 50% +10% from the Glyph so in total it would be: [1+0.22*948+0.14*1116] + 60% = 585.28 
Screenshot below shows that Judgmenet of Vengeance hits the dummy for 602 which is +15 than standard.

**Screenshots**
https://imgur.com/a/xuL0zcy

**Additional context**
![WoWScrnShot_042119_204001](https://user-images.githubusercontent.com/49388783/56474769-5cf52900-6476-11e9-813e-54dc3d3ebe9a.jpg)
![WoWScrnShot_042119_203513](https://user-images.githubusercontent.com/49388783/56474778-7e561500-6476-11e9-8686-e6a4b2ed2b12.jpg)

**Comment by D-CellX** [comment]
The Blizzard Formula [0.013*SPH+0.025*AP*5] used in calculations is not executed the same on a WOW Emulator. The formula used to calculate damage output is very similar but no way works in the same manner. That being said, we are going to take a much closer look and update this post if any fixes are applied. Thank you

**Comment by Min0rity81** [comment]
So it isnt broken then?
