### ISSUE TITLE
Dancing Rune Weapon

### ISSUE THREAD

**Issue by Lordmatsi** [RR2739-VCN/Redrum-PvP#19]
**Describe the bug**
DRW weapon wont attack, i just hovers in the air doing nothing.

**To Reproduce**
1. Cast Spell/Ability: Dancing Rune Weapon/ Dancing Rune Blade
2. Attack Anything
**Expected behavior**
It is supposed to copy the dk's attacks.

**Additional context**

**Comment by D-CellX** [comment]
Unfortunately at this moment, more research is needed to apply fix for this infamous non working spell. So far few teams are working on developing a fix for it. I will update this thread regularly
