### ISSUE TITLE
Hunter Pet Talents

### ISSUE THREAD

**Issue by Lordmatsi** [RR2739-VCN/Redrum-PvP#20]
**Describe the bug**
Some of the hunter pet talents don't work. For example Wild Hunt.

**To Reproduce**
1. Put points into passive talents for pet
2. Watch as nothing happens

**Expected behavior**
Stamina and damage for pets should increase

**Screenshots**
![WoWScrnShot_042919_121508](https://user-images.githubusercontent.com/49250483/56890160-faed8280-6a78-11e9-96c2-77c9f804f150.jpg)
![WoWScrnShot_042919_121721](https://user-images.githubusercontent.com/49250483/56890161-faed8280-6a78-11e9-8f37-cf08ec01a917.jpg)
![WoWScrnShot_042919_121724](https://user-images.githubusercontent.com/49250483/56890162-faed8280-6a78-11e9-9f95-185149a14fde.jpg)

**Comment by D-CellX** [comment]
Duplicate #16
