### ISSUE TITLE
Shadowflame

### ISSUE THREAD

**Issue by MeVeryConfusion** [RR2739-VCN/Redrum-PvP#22]
Shadow flame is a warlock aoe spell.
With glyph it applies non magic 70% movement slow.

Issue:
The spell ignores Anti-Magic Shell (should give full immunity against spells and its effects).

How it should work:
If the warlock uses the Shadowflame spell on a dk with an active Anti-Magic Shell, It should totally ignore the dmg (infront dmg and dot aswell) and the non magic debuff aswell.

![WoWScrnShot_050519_180937](https://user-images.githubusercontent.com/50236754/57196891-5e881c00-6f61-11e9-8f9d-f6ec6b37b430.jpg)

**Comment by D-CellX** [comment]
Shadowflame has SPELL_ATTR3_IGNORE_HIT_RESULT, so i recon it should ignore AMS.
Some "blizzard" sources say that glyph of shadowflame should ignore ams)
If someone can find any good proof on it, i can reopen, but until then it's closed.

**Comment by D-CellX** [comment]
Reconfirmed with TC ignore attributes in place
