### ISSUE TITLE
 [Righteous Vengeance]

### ISSUE THREAD

**Issue by MeVeryConfusion** [RR2739-VCN/Redrum-PvP#25]
Issue:
The spell on 3/3 talent is not proccing the debuff  on spells it should.

How it should work:
After scoring a critical strike with judgement,crusader strike or divine storm; the abilities should procc a debuff with a DOT  according to this talent.
on 1/3 and 2/3 the debuff is working fine
![WoWScrnShot_050519_195255](https://user-images.githubusercontent.com/50236754/57198175-14f2fd80-6f70-11e9-8078-3fe4cea84de3.jpg)
![WoWScrnShot_050519_195303](https://user-images.githubusercontent.com/50236754/57198176-1b817500-6f70-11e9-9663-1227330865ec.jpg)

but with 3/3 point on this talent. doesnt work:
![WoWScrnShot_050519_195937](https://user-images.githubusercontent.com/50236754/57198192-54b9e500-6f70-11e9-88c2-8b8e964022a1.jpg)

**Screenshots**

**Additional context**

**Comment by D-CellX** [comment]
This issue is now fixed. Thank you @MeVeryConfusion
