### ISSUE TITLE
Freezing Band + 	Deadman's Hand Proc

### ISSUE THREAD

**Issue by MeVeryConfusion** [RR2739-VCN/Redrum-PvP#26]
Both of the rings do proc way too much (nearly 100%).
Makes the enemy for melees untouchable in a way.

How it should work: 
Both items have very low proc chance:
e.g.: 
Freezing Band
-Equip: When struck in combat has a 1% chance of inflicting 50 Frost damage to the attacker and freezing them for 5sec.

Both rings need to have reduced chances to blizzlike.

**Comment by D-CellX** [comment]
We are going to correct the PPM Rate on both rings, thank you
