### ISSUE TITLE
Death Grip

### ISSUE THREAD

**Issue by MeVeryConfusion** [RR2739-VCN/Redrum-PvP#27]
The spell Death Grip acts like hunter auto attacks, with minimum range indicator(seems to be like 10-15yd).
When casted on play target the animation is super slow, sometimes take more than 5 secs till the target is pulled to the dk.

**Comment by TonyFonTony** [comment]
I am not sure what you mean by minimum range, but I have seen no indication of the spell NOT working at any range under 30 yards.

As far as the length of time it takes the enemy to reach the casting character, even at the max range, the time is almost exactly the same as when it is used at melee range. At every distance I tested, it takes under 2 seconds for the enemy to reach my character.

**Comment by MeVeryConfusion** [comment]
I can show you it ingame if you will have any time.

**Comment by someNub** [comment]
Can confirm that it **DOES NOT WORK** in close combat or mid range! 
![death grip](https://user-images.githubusercontent.com/30151217/58960025-94a9fd00-87a6-11e9-959e-ce5f913d6408.JPG)
![death grip2](https://user-images.githubusercontent.com/30151217/58960110-c0c57e00-87a6-11e9-8f38-1d930968189c.JPG)

**Comment by Dapper-Cell** [comment]
Confirmed @TonyFonTony 
Issue is now closed
