### ISSUE TITLE
[The Last Line Of Defense] 

### ISSUE THREAD

**Issue by Dotcom92** [RR2739-VCN/Redrum-PvP#3]
Zone- Icecrown

The Frostbrood Destroyer's heal faster then u can kill them

How the quest should work-
https://www.youtube.com/watch?v=8sD5UN067m8

**Comment by D-CellX** [comment]
#4 related, wrong smart_scripts. applied a fix and now working

**Comment by D-CellX** [comment]
Issue #4 is closed.
