### ISSUE TITLE
Bladestorm Slow

### ISSUE THREAD

**Issue by someNub** [RR2739-VCN/Redrum-PvP#32]
**Describe the bug**
Warriors can get slowed during Bladestorm.

**To Reproduce**
1. Start casting Frostbolt on a Mage.
2. Do NOT use Bladestorm before the Mage finishes Frostbolt!
3. Do NOT use Bladestorm after the Frostbolt hits the Warrior!
4. Use Bladestorm when the Frostbolt travels midair towards the Warrior!
5. When the Frostbolt hits, the Warrior will be slowed.

**Expected behavior**
Warriors should not be able to be slowed during Bladestorm.

**Screenshots**
![slow](https://user-images.githubusercontent.com/30151217/58957768-9cb36e00-87a1-11e9-9bcb-842cf6cd3d40.png)

**Additional context**
Warrior can also be slowed in times of lag.

**Comment by D-CellX** [comment]
That is a blizzlike mechanic and happens even on retail up until Legion.
https://eu.battle.net/forums/en/wow/topic/17614111418
