### ISSUE TITLE
Howling Fjord Quest: Meet Lieutenant Icehammer...(ID=11427)

### ISSUE THREAD

**Issue by MeVeryConfusion** [RR2739-VCN/Redrum-PvP#33]
**Describe the bug**
After the quest is taken, there is an option given by Guard Captain Zorek which fastens the way to your given location, meeting Lieutenant Icehammer. (See in Screenshot 1)
When you click on the given option, the whole world phases out and you get fatigue debuff.
After relogging you are spawned in the middle of nowhere, in the Frozen Sea. (Screenshot 2 and 3)
**To Reproduce**
1. Take the quest
2. Click on  "Take me to Lieutenant Icehammer, Zorek!"
3. See the described bugs.

**Expected behavior**
When clicking on the interaction possible, you shall mount a gryphon and fly to Icehammers location.
**Screenshots**
![WoWScrnShot_060519_134310](https://user-images.githubusercontent.com/50236754/58953924-0890d900-8798-11e9-9b6e-7943f7863542.jpg)
![WoWScrnShot_060519_134345](https://user-images.githubusercontent.com/50236754/58953935-12b2d780-8798-11e9-8168-ee21a91b8873.jpg)
![WoWScrnShot_060519_134606](https://user-images.githubusercontent.com/50236754/58954037-4aba1a80-8798-11e9-9815-edd45e33a866.jpg)

**Additional context**
If mounted when taking the option, nothing happens (as nothing should), but at least no phase out.

**Comment by Dapper-Cell** [comment]
The issue is now resolved. Will be applied on the next reboot. Thank you
