### ISSUE TITLE
Shadowfiend Damage

### ISSUE THREAD

**Issue by someNub** [RR2739-VCN/Redrum-PvP#34]
**Describe the bug**
Shadowpriest Shadowfiend most likely hits too hard, based on comparison with several other servers with the same gear (seems like almost twice the damage).

**Expected behavior**
Expected: Hits around 1400 damage on training dummys.
Actual: Hits around 2400 to 2700 damage on training dummys.

**Comment by D-CellX** [comment]
The dmg calculations must be done while testing on players and not a dummy since they have all the immunities and no Reselience

**Comment by someNub** [comment]
1800 to 2000 damage on an 1215 resilience frost dk here.
900 to 1000 damage on an 1100 resilience rogue and around 900 damage to unholy dk on other servers.

Dunno how much it did during retail, so I can only compare it to other 3.3.5 servers.

**Comment by D-CellX** [comment]
I will pull the references regarding its damage. We must do the comparison and calculations based of retail. Will update this issue shortly

**Comment by Dapper-Cell** [comment]
The issue is now closed and resolved, recalculations of pet dmg was applied.
