### ISSUE TITLE
Armor to Attackpower Talents

### ISSUE THREAD

**Issue by someNub** [RR2739-VCN/Redrum-PvP#35]
**Describe the bug**
Attackpower doesn't change at armor change. Attackpower is calculated when switching zones or reloging.

**To Reproduce**
1. Use a two-handed weapon.
2. Specc for example as warrior into [Armored to the Teeth](https://wotlk-twinhead.twinstar.cz/?spell=61222).
3. Relog
4. Remember your attackpower
5. Switch to shield for more armor
6. Relog
7. Switch back to two-handed
8. Look at your attackpower and compare it to before
9. You have more attackpower

**Expected behavior**
Change attackpower when your armor value changes.

**Screenshots**
Warrior relog normal with two-handed weapon equiped. **5282 Attackpower**
![relog_normal](https://user-images.githubusercontent.com/30151217/58958081-5f031500-87a2-11e9-9856-77946caf9579.JPG)
Warrior relog with shield equiped. Switched to two-handed afterwards. No other piece of gear changed. **5539 Attackpower**
![relog_shield](https://user-images.githubusercontent.com/30151217/58958087-62969c00-87a2-11e9-974b-c610fd8dbc33.JPG)

**Additional context**
Warriors and Deathknight who specced into armor to attackpower talents can switch zones with full armor gear then switch back to damage gear and still be able to use the full attackpower provided by the armor.
Could also be a display bug and calculated correctly.

**Comment by D-CellX** [comment]
We double checked the database values towards what is displaying and at times it does show you different stats as visual bug but only until you relog
