### ISSUE TITLE
Ghoul cooldown

### ISSUE THREAD

**Issue by someNub** [RR2739-VCN/Redrum-PvP#36]
**Describe the bug**
Sometimes ghoul (Raise Dead) cooldown will not start decreasing. You will not be able to summon your ghoul again until you relog. Gamebreaking in arena, battlegrounds, duels and so forth.

**To Reproduce**
1. Use Death Pact to sacrifice your ghoul during combat.
2. You may have Raise Dead now permanently on cooldown. (I would guess around 5% chance that it happens)
3. If not repeat.

**Expected behavior**
Raise Dead cooldown should always start when your pet dies.

**Screenshots**
TODO

**Additional context**
You can ask any Deathknight who played for a while here, almost everyone encountered this bug. Especially unholy Deathknights.

**Comment by D-CellX** [comment]
We are aware of this issue. It is an issue related to Global Cooldown bug that used to happen with Shadowform.I am going to add a Fizzled Code line to prevent this from happening. Thank you
