### ISSUE TITLE
Howling Fjord Quest: It goes to 11... (ID=11421)

### ISSUE THREAD

**Issue by MeVeryConfusion** [RR2739-VCN/Redrum-PvP#37]
**Describe the bug**
When approaching the Vrykul Harpoon Gun, and using the  Harpoon Control Mechanism(ID=34032) simply nothing happens.Tho the cooldown on the item pops.

**To Reproduce**
1. Use Harpoon Control Mechanism near the Vrykul Harpoon Gun (at the northernmost harpoon building)
3. See that nothing happens.
**Expected behavior**
After using the item at the harpoon gun, you should be able to use it as a vehichle, and start shooting at the building and incoming dragonriders.
This video shows how it should work:
https://www.youtube.com/watch?v=JBiE2hLGqOE
**Screenshots**
No screenshot can describe the problem. So I uploaded this video:
https://youtu.be/_s5cXKY6zN0
**Additional context**
None.

**Comment by D-CellX** [comment]
Fixed, I cannot guarantee that this fix is 100% Blizzlike but the Harpoon Gun should work correctly at the next update. Thank you
