### ISSUE TITLE
Multiclass midair spell Bug

### ISSUE THREAD

**Issue by someNub** [RR2739-VCN/Redrum-PvP#38]
**Describe the bug**
Example Rogue: Midair spells hit the rogue when using vanish, which should not hit the rogue.
Similar to issue #32 

~Is this intended or not? Anyway I'll list everything that would be affected if it actually is a bug.~

**To Reproduce**
1. Start casting Frostbolt on a Mage or any other projectile based cast on any class.
2. Do NOT use Vanish before the Mage finishes Frostbolt!
3. Do NOT use Vanish after the Frostbolt hits the Rogue!
4. Use Vanish when the Frostbolt travels midair towards the Rogue!
5. The Frostbolt will hit the rogue and bring him out of stealth.

**Expected behavior**
The cast should not hit the rogue and the rogue should stay in stealth.

**Additional context**
~Similar spells affected by this bug:~
~- Cloak of Shadows (Rogue will be hit 100% even with 90% resist chance)~
~- Deterence (Hunter will be hit by midair spells even with Deterence buff active)~
~- Spell reflect (midair spells will not be reflected and hit the Warrior)~

**Comment by someNub** [comment]
Ok, after some reasearch Cloak, Deterrence and Spell reflect work as intended this way.
Vanish apparently should grant 0,3s to 0,5s evade chance for the incoming spells, hunter shots should still get them out of stealth tho.

**Comment by Dapper-Cell** [comment]
Confirmed.

**Comment by D-CellX** [comment]
fixed
