### ISSUE TITLE
Hunter Pet Leveling

### ISSUE THREAD

**Issue by someNub** [RR2739-VCN/Redrum-PvP#40]
**Describe the bug**
If you tame your own pet and not use the npc (for different style or color of a pet) you cannot level it up as it is impossible in any way to gain any experience with it. 

**To Reproduce**
1. Tame pet
2. Pet is level 75
3. Kill level 80 monsters
4. Experience in pet window isnt changing
3. Cannot gain any experience eg. by killing level 80 monster

**Expected behavior**
Gain pet experience by killing monsters.

**Comment by D-CellX** [comment]
Fixed
