### ISSUE TITLE
Hall Of Reflection Last Phase

### ISSUE THREAD

**Issue by DevRalph** [RR2739-VCN/Redrum-PvP#44]
Well, at the last boss fight with the LK summoning mobs isn't working at all.
The mobs get summoned behing the LK instead of front of him which buggs the whole fight and lead to a fail (Impossible to be done)

Npc Creature names: 

Raging Ghoul
Risen Witch Doctor
Lumbering Abomination

**PS: This issue is happening in Heroic Mode.**

**Comment by MeVeryConfusion** [comment]
![WoWScrnShot_062719_011056](https://user-images.githubusercontent.com/50236754/60221136-c6c7ef80-9878-11e9-9157-7e88e13e969c.jpg)

He also doesn't walk the path.

**Comment by D-CellX** [comment]
Very interesting. Should we revisit heroic dungeon logic?

**Comment by D-CellX** [comment]
issue resolved.

**Comment by bullsen** [comment]
Dancing Rune Weapon skill of blood dks are not working. When they are cast, they just float and not imitate the dks skills at all.
