### ISSUE TITLE
Event Quest

### ISSUE THREAD

**Issue by MicuentadeWOW** [RR2739-VCN/Redrum-PvP#48]
**Describe the bug**
 [Torch Tossing] quest from Midsummer WoW event dont work at all, the animation and the script work, but it dont count. You have to hit 8 braziers and dont matter how much braziers you hit, at the end of the timer you will fail the quests (i hit like 13 braziers)

**To Reproduce**
1. Use  [Practice Torches]
2. Click on 'Torch Targets' when they got the arrow
3. At the end of the timer you will fail the quest

Aditional information, i only try this at ThunderBluff city and Orgrimmar

**Comment by D-CellX** [comment]
thank you for the report, we will investigate this issue

**Comment by D-CellX** [comment]
related to #43
