### ISSUE TITLE
Arena Crystal: Shadow Sight

### ISSUE THREAD

**Issue by MeVeryConfusion** [RR2739-VCN/Redrum-PvP#50]
Upon interacting with the Crystals the following buffs and debuffs should be added to the player:
-Stealth Detection.
-Invisibility Detection.
-Increases damage taken by 5%.

You don't get the buff(well sometimes, but it should work 100%)
After few tries, I couldn't even pick up the crystals.

**Comment by D-CellX** [comment]
Going to assign @Dapper-Cell to this. I have applied a fix for it few months back but it seems as if this Gameobject sometimes doesnt apply the buff, sometimes it does. Need to dig a bit dipper.
