### ISSUE TITLE
Important! Argent Tournament quest

### ISSUE THREAD

**Issue by Elounia** [RR2739-VCN/Redrum-PvP#52]
**Describe the bug**

At the start of the Argent Tournament quests, which lead to necessary dailies, you have to use a mount which requires Argent Lance. This item should be given from the three questgivers but werent. 

**To Reproduce**
1. Cast Spell/Ability '...'
3. See error or bug

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Lycan74** [comment]
You can get a lance from one of the weapon racks located around the Argent Tournament. The quests involving the lance also work correctly.

**Comment by D-CellX** [comment]
Confirmed. Lances must be acquired from the lance rack
