### ISSUE TITLE
Quest- Escape from the Catacombs NPC not working properly

### ISSUE THREAD

**Issue by Mioizumaki** [RR2739-VCN/Redrum-PvP#55]
![WoWScrnShot_081919_162024](https://user-images.githubusercontent.com/49710328/63300262-6617ca80-c29d-11e9-9ab6-e9762e11efa4.jpg)
There was a server restart while I had been running her through the catacombs so unsure if that is what caused it but she will not move despite opening cage and gives the dialogue as in the screen shot.

**Comment by D-CellX** [comment]
Tested. Works. Please test again
