### ISSUE TITLE
Game crashing at the Argent Tournament Grounds in Icecrown

### ISSUE THREAD

**Issue by Lycan74** [RR2739-VCN/Redrum-PvP#58]
As stated in the title, I was flying through the argent tournament grounds. I was able to goto the main tent to initiate the first quest in the Argent Tournament (that leads me to the Alliance tent in order to begin my training). As i was flying to the Alliance tent my game crashed and I received a WoW Error and then my game would crash (without receiving an error report) everytime I logged into that character (name is Nergal). 
I was able to fix my character by using the teleport hub on the UCP on the website and I have not returned there since. I will attach the crash report to this post.

[2019-08-19 18.50.44 Crash.txt](https://github.com/RR2739-VCN/Vengeful-WoW/files/3522187/2019-08-19.18.50.44.Crash.txt)

**Comment by rmcendre** [comment]
This has also happened to me, I was both flying in on a grif, as well as flying my own mount when it happened.

**Comment by D-CellX** [comment]
Can you also post a crash log?

**Comment by D-CellX** [comment]
Issue is resolved. Will yake effect after reboot
