### ISSUE TITLE
[The Blessing of Zim'Abwa]

### ISSUE THREAD

**Issue by Dotcom92** [RR2739-VCN/Redrum-PvP#6]
Zone-Zul'Drak

Quest npc will not speak to you. 

Video of how the quest should work-
https://www.youtube.com/watch?v=SQPx7GtRlV0

**Comment by D-CellX** [comment]
Fixed applied to Redrum

**Comment by D-CellX** [comment]
issue #6 is closed. confirm now works as intended.
