### ISSUE TITLE
Quest not working

### ISSUE THREAD

**Issue by Zaarkie** [RR2739-VCN/Redrum-PvP#60]
Rogue Quest non functional

Take quest: Deep Cover from Rogue trainer
Go to The Barrens and locate Taskmaster Fizzule
Fire off 2 Flares from Flare Gun provided by the quest
Taskmaster Fizzule remains hostile

**Expected behavior**
Taskmaster Fizzule should become friendly to turn in the quest Deep Cover

**Comment by Duratans** [comment]
When the tower is in sight, use the Flare Gun to signal your arrival to Taskmaster Fizzule. Fire off TWO flares, then approach Taskmaster Fizzule and perform the **Shattered /Salute.**

These actions must be performed in the correct order, as Fizzule will attack and terminate any person he does not recognize.

**Comment by Duratans** [comment]
You have to do 2 flares then target him and type  **/salute**
Quest Works fine
