### ISSUE TITLE
Quest / Reputation

### ISSUE THREAD

**Issue by Elounia** [RR2739-VCN/Redrum-PvP#63]
**Describe the bug**
(Maydie)

I am exalted with Netherwing but the mobs at Netherwing Ledge remain hostile. I grinded the way to exalted. I want to purchase my Netherwing mount from NPCID 23489.

**To Reproduce**
1. Get Exalted with Netherwing through quest and grind
2. Get disappoint :(

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by D-CellX** [comment]
Thank you for the report it will be fixed now

**Comment by TonyFonTony** [comment]
Did you check your reputation tab to see if you are "at war" with them still?

**Comment by Elounia** [comment]
Even though I already grinded myself to Exalted, I still needed to go further into the quest line to pickup the quest "In service of the Illidari". 

I apologize for the inconvenience.

![WoWScrnShot_090219_070159](https://user-images.githubusercontent.com/54259402/64091370-17176e00-cd50-11e9-9877-1c439628ec3c.jpg)
