### ISSUE TITLE
Ice Thistle Yeti - No Model

### ISSUE THREAD

**Issue by Lycan74** [RR2739-VCN/Redrum-PvP#64]
The Ice Thistle Yeti in Winterspring (https://www.wowhead.com/npc=7458/ice-thistle-yeti) do not load correctly, instead they appear as a yeti that is solid green with no correct textures.

![ice thistle yeti](https://user-images.githubusercontent.com/54330250/63544288-d703f000-c4f2-11e9-8e51-cdcc51dcad42.png)

Edit: A rare yeti in Winterspring by the name of Mezzir the Howler (https://www.wowhead.com/npc=10197/mezzir-the-howler) has the same problem
Edit2: Seems any yeti that shares the model appear this way.  Rogue Ice thistle (https://www.wowhead.com/npc=7457/rogue-ice-thistle) is also solid green

**Comment by D-CellX** [comment]
Thank you. Will be fixing it now

**Comment by D-CellX** [comment]
fixed
