### ISSUE TITLE
Incorrect Model - Mount

### ISSUE THREAD

**Issue by Lycan74** [RR2739-VCN/Redrum-PvP#68]
The mount Big Battle Bear (https://www.wowhead.com/item=38576/big-battle-bear) uses the wrong model. It uses the Vicious War Turtle model (https://www.wowhead.com/item=143648/vicious-war-turtle), which strangely enough is the same model that the mammoth calves in Borean Tundra also use (which i've already reported).

**Comment by D-CellX** [comment]
Fixed
