### ISSUE TITLE
Wintergrasp 2

### ISSUE THREAD

**Issue by Zukain2** [RR2739-VCN/Redrum-PvP#69]
**Describe the bug**
Overnight all of the npcs at wintergrasp seem to have gone missing, as well as WG no longer starting

**To Reproduce**
1. Visit wintergrasp
2. Look for the shops/quest npcs
3. Check start timer
4. It's frozen at the same time

**Expected behavior**

**Screenshots**
https://imgur.com/a/IAslLRK
**Additional context**

**Comment by D-CellX** [comment]
WG is disabled until further notice
