### ISSUE TITLE
Gargoyle DK pet not doing enough Damage 

### ISSUE THREAD

**Issue by Astrono1293** [RR2739-VCN/Redrum-PvP#7]
I tried on several occasions to make a DK and spec Holy, however due to Gargoyle not working correctly, I chose not to play DK.

The dmg is very low and sometimes hits only for 99 DPS. Which is very low.

How to reproduce:
Spec Holy, Summon Gargoyle, test dmg.

Thank you

**Comment by D-CellX** [comment]
@Astrono1293 thank you for the report. However few days ago, I already applied a fix for it, Please double check in game as after few tests, DK Gargoyle pet now does way more dmg.
Thank you

**Comment by D-CellX** [comment]
issue #7 is now closed
