### ISSUE TITLE
PvP Rating in 1v1

### ISSUE THREAD

**Issue by AvatarRoku112** [RR2739-VCN/Redrum-PvP#71]
PVP Rating system doesn't work for acquiring gear that requires pvp rating, belt, boots currently.

I expected when I had 1400 rating after the next arena flush to be able to purchase the belt and boots, 1300, and 1400 rating.

**Comment by D-CellX** [comment]
few changes were applied, please test,. try buying a rating required item

**Comment by AvatarRoku112** [comment]
Can purchase now, thank you!

**Comment by D-CellX** [comment]
Thank you
