### ISSUE TITLE
Hunter pets 

### ISSUE THREAD

**Issue by Chillyrage** [RR2739-VCN/Redrum-PvP#79]
Once level 80 and taming a new pet as a hunter. The pet no longer receives exp to level anymore past 75 and in turn gimping BM as the pet would be paper and hold no aggro even with misdirection.

**Comment by D-CellX** [comment]
Blizzlike Behavior, Once you are Level 80 your experience is off, you gain 0 therefore your Pet cannot level. Turn your Experience on by typing .rate xp 12
