### ISSUE TITLE
Charge

### ISSUE THREAD

**Issue by PandaBearLove** [RR2739-VCN/Redrum-PvP#8]
Charge intercept and Intervene Love to throw me under the map :3 
![WoWScrnShot_032819_163922](https://user-images.githubusercontent.com/49079120/55261365-0a579100-526b-11e9-8c7c-08e2295c93fd.jpg)

**Comment by D-CellX** [comment]
This is related to the same issue #10 . confirmed, labeled. thank you

**Comment by D-CellX** [comment]
this issue should be corrected with the last server update,
