### ISSUE TITLE
Judgement of Wise

### ISSUE THREAD

**Issue by Awkakelen** [RR2739-VCN/Redrum-PvP#81]
Judgement of Wise- a talent in paladin's retribution tree should grant 25% base mana and grant a Replenishment effect for him and party/raid members (just like the talent says). It doesn't work at all, it does nothing.

**Comment by D-CellX** [comment]
There is an Issue Report Template that must be used when reporting anything on Github. Edit your report and follow the format

**Comment by D-CellX** [comment]
The Spell reported works as intended. Invalid report
