### ISSUE TITLE
Seal of Command

### ISSUE THREAD

**Issue by Awkakelen** [RR2739-VCN/Redrum-PvP#82]
Seal of Command should also proc while doing spells, but it doesn't. For example, when I'm hitting with Crusader Strike (while this seal is on) it's not transfering the damage to the other target (up to two).

**Comment by D-CellX** [comment]
There is an Issue Report Template that must be used when reporting anything on Github. Edit your report and follow the format

**Comment by D-CellX** [comment]
Spell works as intended. Invalid report
