### ISSUE TITLE
Sindragosa IceTomb/BlisteringCold

### ISSUE THREAD

**Issue by LogickVengefulWoW** [RR2739-VCN/Redrum-PvP#96]
**Describe the bug**
During the third phase of the Sindragosa encounter, Ice Tomb and Blistering Cold abilities happen simultaneously against the raid group. This leads to the raid being pulled under the boss just as the target is hit with Ice Tomb - freezing the entire raid underneath Sindragosa.

**To Reproduce**
1. Fight Sindragosa in phase 3
2. Player is marked for tomb
3. Raid is pulled in
4. Raid is frost tombed immediately

**Expected behavior**
From watching videos, I believe the expected behavior is for the tomb to land on its target 2-4 seconds before the raid is pulled in for blistering cold.

**Screenshots**
None available, currently.

**Additional context**

**Comment by D-CellX** [comment]
Are you sure you compared the encounter description with your bug report?
Can you provide a reference from wowwikki? 
So we can compare the scripting of this encounter? A video or a reference of encounter and its 3rd phase discrepancy
https://wowwiki.fandom.com/wiki/Sindragosa_(tactics)

**Comment by chelu007** [comment]
https://www.wowhead.com/spell=69712/ice-tomb#used-by-npc

**Comment by chelu007** [comment]
https://www.wowhead.com/spell=70123/blistering-cold
https://www.wowhead.com/spell=69712/ice-tomb
These 2 are the spells that are problematic. They happen at the same time. (I didn't use wowwiki links cause they're busted)

https://youtu.be/o89tT2o87r0?t=306
https://youtu.be/B_HZPgLVBGE?t=317
 As you can see the ice tomb drops and only a few seconds later the blistering cold pulls everyone in. I have checked multiple videos of the encounter and in all of them the time between ice tomb dropping and blistering pulling is 2-4 seconds.
In our case, someone gets targeted by the ice tomb and the second we are pulled in by Blistering the tomb drops and freezes everyone.  There is no way to avoid it.

**Comment by D-CellX** [comment]
Please retest again and let us know if any issues arise again with the timing of these 2 spells.
Corrections were applied to https://www.wowhead.com/spell=70123/blistering-cold being casted almost instantly after Ice Tomb., 
Increased it to 4 seconds as it shows in the video. 
Going to leave this issue open until @LogickVengefulWoW retests it.

**Comment by D-CellX** [comment]
Issue is now resolved.
